# DockerSW: 将同一个 SWCLI payload 链接到任意默认镜像
ARG IMAGE
ARG PAYLOAD_IMAGE

FROM ${PAYLOAD_IMAGE} AS swcli-payload
FROM ${IMAGE} AS swcli-delivery

COPY --link --from=swcli-payload / /

WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/entrypoint.sh", "/usr/local/bin/entrypoint-cli.sh"]
CMD ["/bin/bash"]
